### ISSUE TITLE
Can't find package.json

### ISSUE THREAD

**Issue by craigsketchley** [phips28/gh-action-bump-version#7]
I'm getting an error when using this even though `package.json` does exist...

```
Error: package.json could not be found in your project's root. 
    at Toolkit.getPackageJSON (/node_modules/actions-toolkit/lib/index.js:158:19)
    at /index.js:11:21
    at Function.<anonymous> (/node_modules/actions-toolkit/lib/index.js:109:31)
    at step (/node_modules/actions-toolkit/lib/index.js:43:23)
    at Object.next (/node_modules/actions-toolkit/lib/index.js:24:53)
    at /node_modules/actions-toolkit/lib/index.js:18:71
    at new Promise (<anonymous>)
    at __awaiter (/node_modules/actions-toolkit/lib/index.js:14:12)
    at Function.Toolkit.run (/node_modules/actions-toolkit/lib/index.js:100:16)
    at Object.<anonymous> (/index.js:10:9)
```

I'll keep digging to see if I can figure out why.

**Comment by craigsketchley** [comment]
That was using version `5.0.18`, it now seems to working using `master`.

**Comment by phips28** [comment]
Master is the same as 5.0.18
Do you have your package.json in the root of your project?

**Comment by craigsketchley** [comment]
Ah sorry I missed your response on this - yes, I did have `package.json` at my project root. If I get time I'll try to get a simple project up that reproduces the error.
