### ISSUE TITLE
Error when rerunning Action

### ISSUE THREAD

**Issue by glumb** [phips28/gh-action-bump-version#73]
I clicked the rerun button in GitHub and this resulted in the following error:

```console

messages: [
  'fix: script page changed event\nundefined',
  'fix: editor yt iframe background\nundefined',
  'fix: form translation save and preselect languages\nundefined',
  'fix(creator): hide lang prop and expand translations\nundefined',
  'fix(CF): combine asid change listeners\nundefined',
  'feat: prerelease changes\n\nCloses #77\nundefined',
  'feat: usage hints\n\nCloses #69\nundefined',
  'fix: ts type missing\nundefined',
  'feat(form): comment response display\n\nCloses #78\nundefined',
  'fix(form): rename file to image upload\nundefined',
  "Merge branch 'stage' into dev\nundefined",
  "Merge branch 'dev' into stage\nundefined"
]
currentBranch: stage
current: 0.6.0 / version: minor
current: 0.6.0 / version: minor
new version: v0.7.0
git commit failed because you are using "actions/checkout@v2"; but that doesnt matter because you dont need that git commit, thats only for "actions/checkout@v1"
✖  fatal     Error: Command failed: git push ***github.com/glumb/repo.git --follow-tags 
To https://github.com/glumb/repo.git
 ! [rejected]        stage -> stage (fetch first)
error: failed to push some refs to '***github.com/glumb/repo.git'
hint: Updates were rejected because the remote contains work that you do
hint: not have locally. This is usually caused by another repository pushing
hint: to the same ref. You may want to first integrate the remote changes
hint: (e.g., 'git pull ...') before pushing again.
hint: See the 'Note about fast-forwards' in 'git push --help' for details.

    at makeError (/node_modules/execa/index.js:174:9)
    at /node_modules/execa/index.js:278:16
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at async /index.js:118:7
✖  fatal     Failed to bump version
```

**Comment by phips28** [comment]
rerunning is not supported
